FILEDIR = './files'
USER_DB_FILENAME = 'user.db'
CACHE_DB_FILENAME = 'cache.db'
CONTEST_WRITERS_JSON_FILE = 'contest_writers.json'
NOTO_SANS_CJK_FONT_PATH = 'tle/assets/fonts/NotoSansCJK-Bold.ttc'
NOTO_SANS_CJK_FONT_URL = 'https://noto-website-2.storage.googleapis.com/pkgs/NotoSansCJK-Bold.ttc.zip'
