FILEDIR = './files'
USER_DB_FILENAME = 'user.db'
CACHE_DB_FILENAME = 'cache.db'
CONTEST_WRITERS_JSON_FILE = 'contest_writers.json'
NOTO_SANS_CJK_BOLD_FONT_PATH = 'tle/assets/fonts/NotoSansCJK-Bold.ttc'
NOTO_SANS_CJK_REGULAR_FONT_PATH = 'tle/assets/fonts/NotoSansCJK-Regular.ttc'
